filippo.io/age:
- CAPABILITY_OPERATING_SYSTEM
- CAPABILITY_RUNTIME
github.com/bodgit/sevenzip:
- CAPABILITY_CGO
- CAPABILITY_EXEC
- CAPABILITY_MODIFY_SYSTEM_STATE
github.com/charmbracelet/bubbletea:
- CAPABILITY_MODIFY_SYSTEM_STATE
github.com/dsnet/compress/bzip2:
- CAPABILITY_UNANALYZED
github.com/dsnet/compress/internal/prefix:
- CAPABILITY_UNANALYZED
github.com/fatih/color:
- CAPABILITY_FILES
github.com/fsnotify/fsnotify:
- CAPABILITY_READ_SYSTEM_STATE
github.com/go-viper/mapstructure/v2:
- CAPABILITY_REFLECT
github.com/godbus/dbus/v5:
- CAPABILITY_UNSAFE_POINTER
github.com/gopasspw/gopass/internal/store/root:
- CAPABILITY_FILES
github.com/gopasspw/gopass/pkg/gopass/api:
- CAPABILITY_FILES
github.com/klauspost/compress/internal/cpuinfo:
- CAPABILITY_ARBITRARY_EXECUTION
github.com/klauspost/compress/zstd:
- CAPABILITY_ARBITRARY_EXECUTION
github.com/mholt/archives:
- CAPABILITY_CGO
- CAPABILITY_EXEC
- CAPABILITY_MODIFY_SYSTEM_STATE
- CAPABILITY_UNANALYZED
github.com/twpayne/go-shell:
- CAPABILITY_CGO
- CAPABILITY_UNSAFE_POINTER
github.com/zalando/go-keyring:
- CAPABILITY_UNSAFE_POINTER
github.com/zricethezav/gitleaks/v8/detect:
- CAPABILITY_CGO
- CAPABILITY_EXEC
- CAPABILITY_MODIFY_SYSTEM_STATE
- CAPABILITY_UNANALYZED
github.com/zricethezav/gitleaks/v8/sources:
- CAPABILITY_CGO
- CAPABILITY_EXEC
- CAPABILITY_MODIFY_SYSTEM_STATE
- CAPABILITY_UNANALYZED
go.etcd.io/bbolt:
- CAPABILITY_SYSTEM_CALLS
go4.org/readerutil:
- CAPABILITY_CGO
- CAPABILITY_EXEC
- CAPABILITY_MODIFY_SYSTEM_STATE
golang.org/x/sys/unix:
- CAPABILITY_SYSTEM_CALLS
