linters:
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - dupl
  - errcheck
  - errorlint
  - exhaustive
  - exportloopref
  - forbidigo
  - gci
  - gochecknoinits
  - gocritic
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - golint
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - interfacer
  - makezero
  - misspell
  - paralleltest
  - prealloc
  - predeclared
  - rowserrcheck
  - scopelint
  - sqlclosecheck
  - staticcheck
  - structcheck
  - stylecheck
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace
  disable:
  - exhaustivestruct
  - funlen
  - gochecknoglobals
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goheader
  - gomnd
  - lll
  - maligned
  - nakedret
  - nestif
  - nlreturn
  - noctx
  - nolintlint # FIXME renable
  - testpackage
  - wrapcheck
  - wsl

linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/twpayne/chezmoi
  misspell:
    locale: US

issues:
  exclude-rules:
  - linters:
    - goerr113
    text: "do not define dynamic errors, use wrapped static errors instead"
  - linters:
    - dupl
    path: "secretgopass.go"
  - linters:
    - dupl
    path: "secretpass.go"
  - linters:
    - nolintlint
    - paralleltest
    path: "^main_test.go$"
  - linters:
    - forbidigo
    - gochecknoinits
    - paralleltest
    path: cmd/
  - linters:
    - gochecknoinits
    path: internal/chezmoi/chezmoi_unix.go
  - linters:
    - forbidigo
    - gosec
    path: internal/cmd/
  - linters:
    - paralleltest
    path: internal/
  - linters:
    - gosec
    - scopelint
    path: "_test\\.go"
