linters:
  enable-all: true
  disable:
  - funlen
  - gochecknoglobals
  - gocognit
  - goconst
  - gocyclo
  - godox
  - gomnd
  - lll
  - maligned
  - wsl

issues:
  exclude-rules:
  - linters:
    - dupl
    path: "secretgopass.go"
  - linters:
    - dupl
    path: "secretpass.go"
  - linters:
    - gochecknoinits
    path: cmd/
  - linters:
    - scopelint
    path: "_test\\.go"