version: '2'
run:
  go: '1.24'
linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - containedctx
  - copyloopvar
  - decorder
  - dogsled
  - dupword
  - durationcheck
  - err113
  - errchkjson
  - errname
  - errorlint
  - exptostd
  - fatcontext
  - forbidigo
  - forcetypeassert
  - funcorder
  - gocheckcompilerdirectives
  - gochecksumtype
  - gocritic
  - godot
  - gomodguard
  - goprintffuncname
  - gosmopolitan
  - grouper
  - iface
  - importas
  - inamedparam
  - interfacebloat
  - intrange
  - loggercheck
  - makezero
  - mirror
  - misspell
  - nilerr
  - nilnesserr
  - noctx
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - tagalign
  - tagliatelle
  - testableexamples
  - testifylint
  - thelper
  - unconvert
  - unparam
  - usestdlibvars
  - usetesting
  - wastedassign
  - whitespace
  - zerologlint
  disable:
  - asasalint
  - contextcheck
  - cyclop
  - depguard
  - dupl
  - exhaustive
  - exhaustruct
  - funlen
  - ginkgolinter
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goheader
  - gomoddirectives
  - gosec
  - ireturn
  - lll
  - maintidx
  - musttag
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - nonamedreturns
  - paralleltest
  - recvcheck
  - testpackage
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl
  settings:
    forbidigo:
      forbid:
      - pattern: ^archive/zip\.
      - pattern: ^compress/gzip\.
      - pattern: ^fmt\.Print.*$
      - pattern: ^ioutil\..*$
      - pattern: ^os\.(DirEntry|ErrExist|ErrNotExist|FileInfo|FileMode|Is.*|Mode.*)$
    gocritic:
      enable-all: true
      disabled-checks:
      - emptyFallthrough
      - hugeParam
      - rangeValCopy
      - unnamedResult
      - whyNoLint
    govet:
      disable:
      - fieldalignment
      - shadow
      enable-all: true
    misspell:
      locale: US
    revive:
      enable-all-rules: true
      rules:
      - name: add-constant
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: empty-block
        disabled: true
      - name: exported
        disabled: true
      - name: filename-format
        arguments:
        - ^[a-z][-0-9_a-z]*(?:\.gen)?\.go$
      - name: flag-parameter
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-control-nesting
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: nested-structs
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: unused-receiver
        disabled: true
    staticcheck:
      checks:
      - all
  exclusions:
    generated: lax
    presets:
    - common-false-positives
    - legacy
    - std-error-handling
    rules:
    - linters:
      - err113
      text: do not define dynamic errors, use wrapped static errors instead
    - linters:
      - forbidigo
      path: ^internal/cmds/
    - linters:
      - forcetypeassert
      path: _test\.go$
    - linters:
      - forbidigo
      path: assets/scripts/generate-commit.go
formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  - golines
  settings:
    gci:
      sections:
      - standard
      - default
      - prefix(github.com/twpayne/chezmoi)
    gofumpt:
      module-path: github.com/twpayne/chezmoi
      extra-rules: true
    goimports:
      local-prefixes:
      - github.com/twpayne/chezmoi
    golines:
      max-len: 128
      tab-len: 4
