run:
  go: '1.19'

linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - decorder
  - depguard
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exportloopref
  - forbidigo
  - forcetypeassert
  - gci
  - gocheckcompilerdirectives
  - gocritic
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - grouper
  - importas
  - ineffassign
  - interfacebloat
  - ireturn
  - lll
  - loggercheck
  - makezero
  - misspell
  - musttag
  - nilerr
  - noctx
  - nolintlint
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagliatelle
  - tenv
  - testableexamples
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
  disable:
  - asasalint
  - cyclop
  - exhaustive
  - exhaustruct
  - funlen
  - ginkgolinter
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goheader
  - gomnd
  - gomoddirectives
  - maintidx
  - maligned
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - nonamedreturns
  - paralleltest
  - testpackage
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl

linters-settings:
  forbidigo:
    forbid:
    - ^archive/zip\.
    - ^compress/gzip\.
    - ^fmt\.Print.*$
    - ^ioutil\..*$
    - ^os\.(DirEntry|FileInfo|FileMode|Is.*|Mode.*)$
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/chezmoi)
  gofumpt:
    extra-rules: true
    module-path: github.com/twpayne/chezmoi
  goimports:
    local-prefixes: github.com/twpayne/chezmoi
  govet:
    disable:
    - fieldalignment
    - shadow
    enable-all: true
  ireturn:
    allow:
    - anon
    - empty
    - error
    - github\.com/charmbracelet/bubbletea\.Model
    - github\.com/charmbracelet/bubbletea\.Msg
    - github\.com/go-git/go-git/v5/plumbing/format/diff\.File
    - github\.com/go-git/go-git/v5/plumbing/format/diff\.Patch
    - github\.com/mitchellh/mapstructure\.DecodeHookFunc
    - github\.com/twpayne/chezmoi/v2/pkg/chezmoi\.ActualStateEntry
    - github\.com/twpayne/chezmoi/v2/pkg/chezmoi\.Encryption
    - github\.com/twpayne/chezmoi/v2/pkg/chezmoi\.Format
    - github\.com/twpayne/chezmoi/v2/pkg/chezmoi\.PersistentState
    - github\.com/twpayne/chezmoi/v2/pkg/chezmoi\.SourceStateOrigin
    - github\.com/twpayne/chezmoi/v2/pkg/chezmoi\.SourceStateEntry
    - github\.com/twpayne/chezmoi/v2/pkg/chezmoi\.System
    - github\.com/twpayne/chezmoi/v2/pkg/chezmoi\.TargetStateEntry
    - github\.com/twpayne/go-vfs/v4\.FS
    - stdlib
  misspell:
    locale: US
  stylecheck:
    checks:
    - all

issues:
  include:
  - EXC0011 # include issues about comments from `stylecheck`
  exclude-rules:
  - linters:
    - goerr113
    text: do not define dynamic errors, use wrapped static errors instead
  - linters:
    - revive
    text: unused-parameter
  - linters:
    - forbidigo
    - gosec
    - lll
    path: ^internal/cmds/
  - linters:
    - forcetypeassert
    - gosec
    - lll
    path: _test\.go$
  - linters:
    - lll
    path: ^pkg/shell/shellcgo\.go$
