linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - contextcheck
  - deadcode
  - depguard
  - dogsled
  - dupl
  - durationcheck
  - errcheck
  - errname
  - errorlint
  - exportloopref
  - forbidigo
  - forcetypeassert
  - gci
  - gocritic
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ifshort
  - importas
  - ineffassign
  - lll
  - makezero
  - misspell
  - nilerr
  - noctx
  - nolintlint
  - prealloc
  - predeclared
  - promlinter
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - structcheck
  - stylecheck
  - tagliatelle
  - tenv
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - wastedassign
  - whitespace
  disable:
  - cyclop
  - exhaustive
  - exhaustivestruct
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goheader
  - gomnd
  - maligned
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - paralleltest
  - testpackage
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl

linters-settings:
  forbidigo:
    forbid:
    - ^fmt\.Print.*$
    - ^ioutil\..*$
    - ^os\.(DirEntry|FileInfo|FileMode|Is.*|Mode.*)$
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/twpayne/chezmoi
  misspell:
    locale: US

issues:
  exclude-rules:
  - linters:
    - goerr113
    text: "do not define dynamic errors, use wrapped static errors instead"
  - linters:
    - forbidigo
    - gosec
    - lll
    path: ^pkg/cmds/
  - linters:
    - gosec
    - lll
    path: "_test\\.go$"
