project_name: chezmoi

before:
  hooks:
  - go mod download

builds:
- binary: chezmoi
  env:
    - CGO_ENABLED=0
  ldflags: "-s -w -X github.com/twpayne/chezmoi/cmd.version={{ .Version }} -X github.com/twpayne/chezmoi/cmd.commit={{ .Commit }} -X github.com/twpayne/chezmoi/cmd.date={{ .Date }}"
  goos:
    - linux
    - darwin
    - freebsd
    - openbsd
    # - dragonfly
    # - netbsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - ''
  ignore:
    - goos: darwin
      goarch: 386
    - goos: linux
      goarch: amd64
- binary: chezmoi
  env:
    - CGO_ENABLED=1
  goos:
    - linux
  goarch:
    - amd64

## generate .tar.gz archives
archive:
  replacements:
    386: i386

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

## generate RPM and DEB packages
nfpm:
  vendor: "Tom Payne <twpayne@gmail.com>"
  homepage: "https://github.com/twpayne/chezmoi"
  maintainer: Tom Payne <twpayne@gmail.com>
  description: "chezmoi is a tool for managing your dotfiles securely across multiple machines."
  license: MIT
  formats:
    - deb
    - rpm
  overrides:
    rpm:
      name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Env.TRAVIS_BUILD_NUMBER }}-{{ .Arch }}"
      replacements:
        amd64: x86_64
        386: i686
        arm: armhfp
        arm64: aarch64
    deb:
      name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Env.TRAVIS_BUILD_NUMBER }}_{{ .Os }}_{{ .Arch }}"
      replacements:
        386: i386
        arm: armel

# generate a homebrew formula and push to github.com/twpayne/homebrew-taps
brew:
  github:
    owner: twpayne
    name: homebrew-taps
  commit_author:
    name: Tom Payne
    email: twpayne@gmail.com
  folder: Formula
  homepage: "https://github.com/twpayne/chezmoi"
  description: "chezmoi is a tool for managing your dotfiles securely across multiple machines."
