project_name: chezmoi

before:
  hooks:
  - go mod download

builds:
- binary: chezmoi
  env:
  - CGO_ENABLED=0
  ldflags: "-s -w -X github.com/twpayne/chezmoi/cmd.version={{ .Version }} -X github.com/twpayne/chezmoi/cmd.commit={{ .Commit }} -X github.com/twpayne/chezmoi/cmd.date={{ .Date }}"
  goos:
  - linux
  - darwin
  - freebsd
  - openbsd
  # - dragonfly
  # - netbsd
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  - ppc64
  - ppc64le
  goarm:
  - ""
  ignore:
  - goos: darwin
    goarch: 386
  - goos: linux
    goarch: amd64
- binary: chezmoi
  ldflags: "-s -w -X github.com/twpayne/chezmoi/cmd.version={{ .Version }} -X github.com/twpayne/chezmoi/cmd.commit={{ .Commit }} -X github.com/twpayne/chezmoi/cmd.date={{ .Date }}"
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64

archive:
  replacements:
    386: i386

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "Merge pull request"
    - "Merge branch"

nfpm:
  vendor: "Tom Payne <twpayne@gmail.com>"
  homepage: "https://github.com/twpayne/chezmoi"
  maintainer: "Tom Payne <twpayne@gmail.com>"
  description: "Manage your dotfiles across multiple machines, securely."
  license: MIT
  formats:
  - deb
  - rpm
  dependencies:
  - git
  overrides:
    rpm:
      name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Env.TRAVIS_BUILD_NUMBER }}-{{ .Arch }}"
      replacements:
        amd64: x86_64
        386: i686
        arm: armhfp
        arm64: aarch64
    deb:
      name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Env.TRAVIS_BUILD_NUMBER }}_{{ .Os }}_{{ .Arch }}"
      replacements:
        386: i386
        arm: armel

brew:
  github:
    owner: twpayne
    name: homebrew-taps
  commit_author:
    name: Tom Payne
    email: twpayne@gmail.com
  folder: Formula
  homepage: "https://github.com/twpayne/chezmoi"
  description: "Manage your dotfiles across multiple machines, securely."

# snapcraft disabled pending:
# https://forum.snapcraft.io/t/request-classic-confinement-for-chezmoi/10903
# https://forum.snapcraft.io/t/invalid-architecture-specified-in-the-manifest-ppc64/10904
# https://github.com/goreleaser/goreleaser/issues/1006
# snapcraft:
#   summary: "Manage your dotfiles across multiple machines, securely."
#   description: "Manage your dotfiles across multiple machines, securely."
#   publish: true
#   grade: devel
#   confinement: classic
