.PHONY: smoketest
smoketest:
	go run . --version
	go test ./...
	./bin/golangci-lint run

all: generate

.PHONY: format
format:
	find . -name \*.go | xargs $$(go env GOPATH)/bin/gofumports -w

.PHONY: generate
generate:
	go generate

.PHONY: install-tools
install-tools:
	curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- v1.25.0
	( cd $$(mktemp -d) && go mod init tmp && go get mvdan.cc/gofumpt/gofumports )

.PHONY: lint
lint:
	./bin/golangci-lint run

.PHONY: release
release:
	goreleaser release \
		--rm-dist \
		${GORELEASER_FLAGS}

.PHONY: test-release
test-release:
	goreleaser release \
		--rm-dist \
		--skip-publish \
		--snapshot \
		${GORELEASER_FLAGS}

.PHONY: test
test:
	go test -race ./...

.PHONY: update-install.sh
update-install.sh:
	# FIXME install.sh is generated by godownloader, but godownloader is
	# currently unmaintained and needs to be run manually:
	# godownloader --repo=twpayne/chezmoi .goreleaser.yaml > assets/scripts/install.sh
	# cp assets/scripts/install.sh scripts/