name: build-docs
on:
  pull_request:
    branches:
    - master
    paths:
    - assets/chezmoi.io/**
    - pyproject.toml
    - uv.lock
    - .github/workflows/build-docs.yml
    - .github/workflows/preview-docs.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
env:
  GO_VERSION: 1.26.2 # https://go.dev/doc/devel/release
  PYTHON_VERSION: '3.14' # https://www.python.org/downloads/
  UV_VERSION: 0.11.7 # https://github.com/astral-sh/uv/releases
  NO_MKDOCS_2_WARNING: 1
jobs:
  build-docs:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-go
      with:
        cache-prefix: website-go
        go-version: ${{ env.GO_VERSION }}
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b   # v8.1.0
      with:
        enable-cache: false
        version: ${{ env.UV_VERSION }}
    - name: install-website-dependencies
      run: |
        uv python install ${{ env.PYTHON_VERSION }}
        uv sync --locked
    - name: build-website
      run: uv run -v task build-docs
      env:
        CHEZMOI_GITHUB_TOKEN: ${{ secrets.CHEZMOI_GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONDONTWRITEBYTECODE: 1
    - name: compute-docs-digest
      run: echo "${{ hashFiles('assets/chezmoi.io/site/**') }}" > assets/chezmoi.io/digest.txt
    - name: upload-docs-preview
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a   # v7.0.1
      with:
        name: docs-site-preview
        path: |
          assets/chezmoi.io/site/
          assets/chezmoi.io/digest.txt
        retention-days: 1
