name: build-docs
on:
  pull_request:
    branches:
    - master
    paths:
    - 'assets/chezmoi.io/**'
    - 'pyproject.toml'
    - 'uv.lock'
    - '.github/workflows/build-docs.yml'
    - '.github/workflows/preview-docs.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
env:
  GO_VERSION: 1.26.2 # https://go.dev/doc/devel/release
  PYTHON_VERSION: '3.14' # https://www.python.org/downloads/
  UV_VERSION: 0.11.3 # https://github.com/astral-sh/uv/releases
jobs:
  build-docs:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-go
      with:
        cache-prefix: website-go
        go-version: ${{ env.GO_VERSION }}
    - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57   # v8.0.0
      with:
        enable-cache: false
        version: ${{ env.UV_VERSION }}
    - name: install-website-dependencies
      run: |
        uv python install ${{ env.PYTHON_VERSION }}
        uv sync --locked
    - name: build-website
      run: uv run -v task build-docs
      env:
        CHEZMOI_GITHUB_TOKEN: ${{ secrets.CHEZMOI_GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload-docs-preview
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f   # v7.0.0
      with:
        name: docs-site-preview
        path: assets/chezmoi.io/site/
        retention-days: 1
