name: htmltest

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        pip install mkdocs-material mkdocs-redirects mkdocs-simple-hooks
        ( cd assets/chezmoi.io && mkdocs build )
    - uses: wjdp/htmltest-action@master
      with:
        path: assets/chezmoi.io/site
        config: assets/chezmoi.io/htmltest.yml
