name: misspell

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request: null

jobs:
  misspell:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # pin@v3
      - name: misspell
        uses: reviewdog/action-misspell@bc3ad2d435c695c1955d4e2e1c3f1762fc6d57dc # pin@v1
        with:
          locale: US
