name: misspell

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:

jobs:
  misspell:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          locale: US
